#!/usr/bin/env python3
"""Generate docs/sample.html -- the screenshot fixture for the README.

    python docs/make_sample.py

It renders the REAL templates and links the real CSS and JS, then injects a
stubbed `fetch` returning an invented fleet. So the picture is the actual
interface, and no real hostname, port or path can end up in a published image.

Generated rather than hand-written on purpose: the first version was a copy of
the markup, and it silently rotted -- it kept a nav item that had been deleted
and lacked three element ids that app.js had come to rely on, so the page threw
on load and rendered an empty list. A fixture that is built from the templates
cannot drift from them.
"""

import io
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "docs", "sample.html")

try:
    from jinja2 import Environment, FileSystemLoader
except ImportError:                                     # pragma: no cover
    sys.exit("needs jinja2 (it comes with flask): pip install -r requirements.txt")

# --------------------------------------------------------------------------- #
# the invented fleet
#
# Chosen to show the states worth photographing: apps running and stopped, one
# on https, one identified by port rather than command line (the `external`
# badge), a version from each source and one with none, and a document.
# --------------------------------------------------------------------------- #

def app(name, label, desc, icon, port, url, version_source, **kw):
    entry = {
        "name": name, "label": label, "description": desc,
        "icon": "../static/icons/%s.svg" % icon,
        "type": "app", "is_self": False, "is_file": False,
        "dir": label.replace(" ", ""), "path": "C:\\Users\\you\\dev\\" + name,
        "path_exists": True, "command": "python", "args": ["app.py"],
        "port": port, "url": url, "match": "%s.app[.]py" % name,
        "autostart": True, "running": True, "pid": 21480, "via": "match",
        "has_logs": True, "file": "", "file_exists": None, "note": "",
    }
    entry.update(kw)
    return entry


SAMPLE = [
    dict(app("launcher", "Apps Launcher",
             "This page - list and registration for the other apps",
             "launcher", 5058, "http://127.0.0.1:5058/", None),
         type="self", is_self=True, pid=4812,
         path="C:\\Users\\you\\dev\\launcher"),
    app("notes-api", "Notes API", "REST API for the notes service",
        "braces", 5055, "http://127.0.0.1:5055/", None, pid=21480),
    app("dashboard", "Metrics Dashboard", "Metrics dashboard, self-signed cert",
        "gauge", 5000, "https://localhost:5000/", None, pid=23468),
    app("inbox-worker", "Inbox Worker", "Background queue worker - email and chat",
        "inbox", 5061, "http://127.0.0.1:5061/", None,
        pid=30800, via="port", has_logs=False),
    app("reports", "Monthly Reports", "Monthly report builder",
        "calendar", 5057, "http://127.0.0.1:5057/", None, pid=35340),
    app("scheduler", "Job Scheduler", "Cron-style job runner - started on demand",
        "default", 5062, "http://127.0.0.1:5062/", None,
        autostart=False, running=False, pid=None, via="none",
        command="node", args=["server.js"], match="Scheduler.server[.]js"),
    {
        "name": "system-snapshot", "label": "System Snapshot",
        "description": "Generated hardware and service snapshot",
        "icon": "../static/icons/file.svg",
        "type": "file", "is_self": False, "is_file": True,
        "dir": "", "path": "", "path_exists": None,
        "command": "", "args": [], "port": None,
        "url": "/open/system-snapshot", "match": "",
        "autostart": False, "running": False, "pid": None, "via": "file",
        "has_logs": False, "note": "",
        "file": "C:\\Users\\you\\docs\\system-snapshot.html", "file_exists": True,
    },
]

VERSIONS = {
    "launcher":        {"version": "1.2.0", "source": "Apps Launcher"},
    "notes-api":       {"version": "v2.3.1", "source": "package.json"},
    "dashboard":       {"version": "v0.9.4", "source": "git describe"},
    "inbox-worker":    {"version": "5736112-dirty", "source": "git describe"},
    "reports":         {"version": "", "source": ""},
    "scheduler":       {"version": "1.4.0", "source": "VERSION"},
    "system-snapshot": {"version": "2026-08-31", "source": "file modified"},
}

FIXTURE = """
  <style>
    /* A live clock would date the screenshot. */
    #tick { display: none; }
  </style>
  <script>
    /* Screenshot fixture -- generated by docs/make_sample.py, do not hand-edit.
       Everything here is invented. */
    const SAMPLE = %(apps)s;
    const VERSIONS = %(versions)s;
    const REPLIES = {
      "/api/status":   { apps: SAMPLE, at: 0, launcher_version: "%(version)s" },
      "/api/versions": { ok: true, versions: VERSIONS, launcher_version: "%(version)s" },
    };
    /* Answer from the fixture instead of the network, so the page needs nothing
       running and cannot accidentally show real data. */
    window.fetch = (url) => {
      const path = String(url).split("?")[0];
      const body = REPLIES[path] || { ok: true, framable: true };
      return Promise.resolve({ ok: true, json: () => Promise.resolve(body) });
    };
  </script>
"""


def url_for(endpoint, **values):
    """Enough of Flask's url_for for a file on disk: static assets sit one
    directory up, and nothing else is navigable in a still."""
    if endpoint == "static":
        return "../static/" + values.get("filename", "")
    return "#"


def main():
    env = Environment(loader=FileSystemLoader(os.path.join(ROOT, "templates")),
                      autoescape=True)
    env.globals["url_for"] = url_for
    # apps=[] so the embedded initial data is empty and the stub supplies it.
    html = env.get_template("index.html").render(page="apps", apps=[])

    marker = "</head>"
    assert marker in html, "the template stopped having a </head>"
    html = html.replace(marker, FIXTURE % {
        "apps": json.dumps(SAMPLE, indent=2),
        "versions": json.dumps(VERSIONS, indent=2),
        "version": VERSIONS["launcher"]["version"],
    } + marker, 1)

    banner = ("<!-- GENERATED by docs/make_sample.py from the real templates.\n"
              "     Edit that script, not this file. -->\n")
    io.open(OUT, "w", encoding="utf-8", newline="\n").write(banner + html)
    print("wrote %s (%d bytes)" % (os.path.relpath(OUT, ROOT), len(html)))


if __name__ == "__main__":
    main()
